---
# general settings
ubuntu_version: jammy
default_username: thomas
default_email: contact@thomassimonet.fr
timezone: Europe/Paris

default_password: "{{ lookup('ansible.builtin.password', '/dev/null length=15 chars=ascii_letters,digits,punctuation') }}"
root_password: "{{ lookup('ansible.builtin.password', '/dev/null length=15 chars=ascii_letters,digits,punctuation') }}"

# vagrant
is_vagrant: true

# ------------------------------------
# Applications
# ------------------------------------

# Hostname
server_hostname: "192-168-56-18.traefik.me"
server_ip_address: "192.168.56.18"

# Traefik
traefik_hostname: "traefik-192-168-56-18.traefik.me"
traefik_version: "v3.0"

# Monitoring
grafana_hostname: "grafana-192-168-56-18.traefik.me"
prometheus_hostname: "prometheus-192-168-56-18.traefik.me"

# ------------------------------------
# End Applications
# ------------------------------------
