---
discord_webhook_backups: "https://discord.com/api/webhooks/1253394894647726080/aDDj3MKO8_iodGzmy7N1-VWyYwt5UyCyEsdwhI7gIfnrrLBFO5umHVoycbJHvZWx9l0-"
discord_webhook_updates: "https://discord.com/api/webhooks/1253456842302947454/-nfGjaCgTfzxGiovStPW5NcTlo0D5kkc-y2z0Kvm92qGDofG1TArctO6-9l_6Doxp-zw"