---
- name: Create directories
  ansible.builtin.file:
    path: /mnt/docker/{{ item.path }}
    state: directory
    owner: "{{default_username}}"
    group: "{{default_username}}"
  with_filetree: templates/
  when: item.state == 'directory'

- name: Template files
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: /mnt/docker/{{ item.path }}
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: 0755
  with_filetree: templates/
  when: item.state == 'file'

- name: Ensure global networks are created
  community.general.docker_network:
    name: "{{ item }}"
    driver: bridge
  become_user: "{{ default_username }}"
  loop:
    "{{ docker_networks }}"

- name: Start all containers
  community.docker.docker_compose_v2:
    project_src: /mnt/docker/{{ item }}
  become_user: "{{ default_username }}"
  loop:
    - "traefik"
    - "portainer"
