---
- name: Create directories
  ansible.builtin.file:
    path: /mnt/docker-volumes/{{ item.path }}
    state: directory
  with_filetree: templates/
  when: item.state == 'directory'

- name: Template files
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: /mnt/docker-volumes/{{ item.path }}
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: 0755
  with_filetree: templates/
  when: item.state == 'file'

- name: Start all containers
  community.docker.docker_compose:
    project_src: /mnt/docker-volumes/{{ item.path }}
  loop:
    - "portainer"
    - "traefik"
