---
- name: Install fail2ban
  ansible.builtin.apt:
    pkg:
      - fail2ban
    state: present

- name: Ensure config files exist
  ansible.builtin.template:
    src: custom.conf
    dest: /etc/fail2ban/jail.d/
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: 0640

- name: Start fail2ban service
  service:
    name: fail2ban
    state: started
  become: true

- name: Enable fail2ban service
  service:
    name: fail2ban
    enabled: true
  become: true