---
- name: Setup homelab
  hosts: all
  become: true
  roles:
    - role: common
    # - role: docker
    # - role: traefik
    # - role: cloudflared
    # - role: grafana
    # - role: backrest
    # - role: uptimekuma
    # - role: diun
    # - role: apprise
    # - role: mealie
    # - role: freshrss
    # - role: karakeep
    # - role: portfolio
    - role: reboot
