---
- name: Setup homelab
  hosts: all
  vars_files:
    - group_vars/all.yml
    - group_vars/env.yml
  become: true

  roles:
    - role: common

    # - role: dotfiles

    - role: docker

    - role: rsyslog

    # applications
    - role: traefik

    - role: monitoring

    - role: openobserve

    - role: diun

    # - role: gotify
    # https://crazymax.dev/diun/notif/gotify/

    # - role: freshrss

    # - role: readeck

    # - role: maelie

    # - role: immich

    # - role: rsshub

    # - role: coder
    # /end applications

    - role: reboot

    # - role: vagrant
