---
- name: Setup homelab
  hosts: all
  become: true
  roles:
    - role: common
    # - role: dotfiles
    - role: docker
    - role: traefik
    - role: cloudflared
    - role: grafana
    - role: diun
    - role: apprise
    - role: restic
    - role: mealie
    - role: freshrss
    - role: readeck
    # /end applications
    - role: reboot
