---
- name: Setup homelab
  hosts: all
  vars_files:
    - group_vars/all.yml
  become: true

  roles:
    - role: common

    - role: dotfiles

    - role: docker

    - role: rsyslog

    - role: reboot

    # applications
    # - role: traefik

    # - role: portainer

    # - role: grafana

    # - role: diun

    # - role: freshrss

    # - role: readeck

    # - role: maelie

    # - role: immich

    # - role: coder
    # /end applications

    # - role: vagrant
