---
- name: Setup homelab
  hosts: all
  vars_files:
    - group_vars/all.yml
    - group_vars/discord.yml
  become: true

  roles:
    - role: common

    - role: dotfiles

    - role: docker

    - role: rsyslog

    # applications
    - role: traefik

    - role: diun

    - role: restic

    - role: apprise

    # - role: freshrss

    # - role: readeck

    # - role: maelie

    # - role: immich

    # - role: rsshub

    # - role: coder
    # /end applications

    - role: reboot
