---
- name: Setup homelab
  hosts: all
  become: true
  roles:
    - role: common

    - role: dotfiles

    - role: docker

    - role: rsyslog

    # applications
    - role: traefik

    - role: diun

    - role: restic

    - role: apprise

    - role: monitoring
    # /end applications

    - role: reboot
