---
- hosts: all
  vars_files:
    - group_vars/all.yml
    - group_vars/apt.yml
  vars:
    is_vagrant: false
  become: true
  roles:
    - role: common

    - role: user

    - role: fail2ban

    - role: ufw

    - role: ssh

    - role: dotfiles

    - role: docker

    - role: rsyslog

    # applications
    - role: traefik

    - role: portainer

    - role: grafana

    # - role: diun

    # - role: freshrss

    # - role: readeck

    # - role: maelie

    # - role: immich

    # - role: coder
    # /end applications

    - role: vagrant
