---
- name: Setup homelab
  hosts: all
  become: true
  roles:
    - role: common
    # - role: dotfiles
    - role: docker
    - role: rsyslog
    # applications
    - role: crowdsec
    - role: traefik
    - role: cloudflared
    # - role: monitoring
    - role: netdata
    # - role: graylog
    # - role: diun
    # - role: restic
    # - role: apprise
    # - role: mealie
    # - role: freshrss
    # - role: readeck
    # - role: zipline
    # /end applications
    - role: reboot
