---
- name: Create directory for Docker's GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Get architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    filename: docker
    state: present

- name: Install Docker and related packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ default_username }}"
    groups: docker
    append: true

- name: Copy docker daemon config
  ansible.builtin.template:
    src: daemon.json
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "root"
    mode: 0644
  notify: restart docker

- name: Enable and start Docker services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - containerd.service

# - name: Add logrotate custom rules for Docker logs
#   ansible.builtin.copy:
#     src: templates/logrotate_docker
#     dest: /etc/logrotate.d/docker
#     owner: root
#     group: root
#     mode: u=rw,g=r,o=r

- name: Ensure global networks are created
  community.general.docker_network:
    name: "{{ item }}"
    driver: bridge
  loop:
    "{{ docker_networks }}"

- name: Create docker compose directories in /home
  ansible.builtin.file:
    path: /home/{{ default_username }}/compose/{{ item }}
    state: directory
    mode: '0755'
  loop:
    - "portainer"
    - "traefik"

- name: Create docker volumes directories in /mnt
  ansible.builtin.file:
    path: /mnt/docker-volumes/{{ item }}
    state: directory
    mode: '0755'
  loop:
    - "portainer"
    - "traefik"

- name: Copy docker compose files
  ansible.builtin.template:
    src: compose/{{ item }}/docker-compose.yml
    dest: "/home/{{ default_username }}/compose/{{ item }}/docker-compose.yml"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: 0755
  loop:
    - "portainer"
    - "traefik"

- name: Copy docker compose files
  ansible.builtin.template:
    src: compose/{{ item }}/docker-compose.yml
    dest: "/home/{{ default_username }}/compose/{{ item }}/docker-compose.yml"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: 0755
  loop:
    - "portainer"
    - "traefik"

- name: Start all containers
  ansible.builtin.shell:
    cmd: docker compose -f /home/{{ default_username }}/compose/{{ item }}/docker-compose.yml up -d
  loop:
    - "portainer"
    - "traefik"
