services:
  gotify:
    image: gotify/server:2.4.0
    container_name: gotify
    hostname: gotify
    environment:
      - GOTIFY_DEFAULTUSER_PASS=custom
    volumes:
      - /mnt/gotify/data:/app/data
    networks:
      - app
      - diun-watch
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.rule=Host(`{{ gotify_hostname }}`)"
      - "traefik.http.routers.gotify.service=gotify"
      - "traefik.http.routers.gotify.entrypoints=https"
      - "traefik.http.routers.gotify.tls=true"
      - "diun.enable=true"

networks:
  app:
    name: app
  diun-watch:
    name: diun-watch