services:
  gotify:
    image: gotify/server:2.4.0
    container_name: gotify
    hostname: gotify
    security_opt:
      - no-new-privileges:true
    environment:
      - GOTIFY_DEFAULTUSER_NAME={{ lookup('ansible.builtin.env', 'gotify_username') }}
      - GOTIFY_DEFAULTUSER_PASS={{ lookup('ansible.builtin.env', 'gotify_password') }}
    volumes:
      - /mnt/gotify/data:/app/data
    networks:
      - app
      - diun-watch
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.rule=Host(`{{ gotify_hostname }}`)"
      - "traefik.http.routers.gotify.service=gotify"
      - "traefik.http.routers.gotify.entrypoints=https"
      - "traefik.http.routers.gotify.tls=true"
      - "traefik.http.services.gotify.loadbalancer.server.port=80"
      - "diun.enable=true"

networks:
  app:
    name: app
  diun-watch:
    name: diun-watch