---
- name: Create main directory
  ansible.builtin.file:
    path: /mnt/docker/linkwarden
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0755"

- name: Create volumes directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0755"
  loop:
    - /mnt/docker/volumes/linkwarden
    - /mnt/docker/volumes/linkwarden/linkwarden
    - /mnt/docker/volumes/linkwarden/postgres
    - /mnt/docker/volumes/linkwarden/meilisearch

- name: Ensure config files exist
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/mnt/docker/linkwarden/{{ item }}"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0644"
  loop:
    - compose.yml

- name: Create linkwarden network
  community.docker.docker_network:
    name: linkwarden
    state: present

- name: Run "docker compose up"
  community.docker.docker_compose_v2:
    project_src: /mnt/docker/linkwarden
    recreate: always
