---
BITWARDEN_TRAEFIK_AUTH_USER_PASSWORD_ID: "{{ lookup('ansible.builtin.env', 'BITWARDEN_TRAEFIK_AUTH_USER_PASSWORD_ID') }}"
TRAEFIK_AUTH_USER_PASSWORD: "{{ lookup('bitwarden.secrets.lookup', BITWARDEN_TRAEFIK_AUTH_USER_PASSWORD_ID, access_token=BITWARDEN_ACCESS_TOKEN) }}"
