services:

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    # environment:
      # - GF_SMTP_ENABLED=true
      # - GF_SMTP_FROM_ADDRESS=${SMTP_FROM:-noreply@example.com}
      # - GF_SMTP_HOST=${SMTP_HOST:-smtp.example.com:587}
      # - GF_SMTP_PASSWORD=${SMTP_PASSWORD:-myp@ssw0rd}
      # - GF_SMTP_USER=${SMTP_USERNAME:-noreply@example.com}
      # - GF_SERVER_ROOT_URL=https://{{ grafana_hostname }}
    # volumes:
      # - /mnt/docker/monitoring/grafana:/var/lib/grafana
    networks:
      - app
      - monitoring
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=https
      - traefik.http.routers.grafana.rule=Host(`{{ grafana_hostname }}`)
      - traefik.http.routers.grafana.service=grafana
      - traefik.http.routers.grafana.tls=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: monitoring-prometheus
    user: 1002:1002
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.size=1GB
      - --web.external-url=https://{{ prometheus_hostname }}
    volumes:
      - /mnt/docker/monitoring/prometheus/data:/prometheus
      - /mnt/docker/monitoring/prometheus/config:/etc/prometheus
    networks:
      - app
      - monitoring
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.entrypoints=https
      - traefik.http.routers.prometheus.rule=Host(`{{ prometheus_hostname }}`)
      - traefik.http.routers.prometheus.service=prometheus
      - traefik.http.routers.prometheus.tls=true
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
      # - traefik.http.routers.grafana-prom.middlewares=grafana-prom-auth
      # - traefik.http.middlewares.grafana-prom-auth.basicauth.users=${PROM_USER:-admin}:${PROM_PASSWORD:-htpasswd}

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: monitoring-cadvisor
    command: -docker_only=true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: monitoring-node-exporter
    environment:
      {{ "- NODE_ID={{.Node.ID}}" }}
    volumes:
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /etc/hostname:/etc/hostname
      - /mnt:/mnt:ro
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    networks:
      - monitoring

networks:
  app:
    name: app
  monitoring:
    name: monitoring