---
- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot machine to finalize setup
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible."
    connect_timeout: 10
    reboot_timeout: 600
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists