---
- name: Reboot if kernel/libs updated and requested by the system
  ansible.builtin.shell: sleep 10 && reboot
  args:
    removes: /var/run/reboot-required
  async: 1
  poll: 0

- name: Wait for system to become reachable again
  ansible.builtin.wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 300
