services:
  gotify:
    image: gotify/server:2.4.0
    container_name: gotify
    hostname: gotify
    security_opt:
      - "no-new-privileges=true"
    environment:
      - "GOTIFY_DEFAULTUSER_NAME={{ lookup('ansible.builtin.env', 'GOTIFY_USERNAME') }}"
      - "GOTIFY_DEFAULTUSER_PASS={{ lookup('ansible.builtin.env', 'GOTIFY_PASSWORD') }}"
    volumes:
      - "/mnt/gotify/data:/app/data"
    networks:
      - "app"
      - "diun-watch"
      - "notification"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.rule=Host(`{{ gotify_hostname }}`)"
      - "traefik.http.routers.gotify.service=gotify"
      - "traefik.http.routers.gotify.entrypoints=https"
      - "traefik.http.routers.gotify.tls=true"
      - "traefik.http.services.gotify.loadbalancer.server.port=80"
      - "diun.enable=true"

networks:
  app:
    external: true
  diun-watch:
    external: true
  notification:
    external: true