---
- name: Create main directory
  ansible.builtin.file:
    path: /mnt/docker/portainer
    state: directory
    owner: "{{default_username}}"
    group: "{{default_username}}"
    mode: "0755"

- name: Create sub directories
  ansible.builtin.file:
    path: /mnt/docker/portainer/{{ item.path }}
    state: directory
    owner: "{{default_username}}"
    group: "{{default_username}}"
    mode: "0755"
  with_filetree: templates/compose/
  when: item.state == 'directory'

- name: Ensure config files exist
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: /mnt/docker/portainer/{{ item.path }}
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0644"
  with_filetree: templates/compose/
  when: item.state == 'file'

- name: Ensure Portainer systemd service is installed
  ansible.builtin.template:
    src: "systemd/portainer.service"
    dest: "/etc/systemd/system/docker-portainer.service"
    mode: "0644"

- name: Make sure Portainer service is running
  ansible.builtin.systemd_service:
    state: started
    name: docker-portainer.service