---
- name: Create a user/group www-data owned by the user and group id of 33
  ansible.builtin.user:
    name: www-data
    create_home: false
    system: true
    shell: /bin/false
    uid: "33"
    groups: "33"
    state: present

- name: Create main directory
  ansible.builtin.file:
    path: /mnt/docker/apprise
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0755"

- name: Create volumes directory
  ansible.builtin.file:
    path: /mnt/docker/volumes/apprise/config
    state: directory
    owner: "33"
    group: "33"
    mode: "0770"

- name: Ensure config files exist
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/mnt/docker/apprise/{{ item }}"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0644"
  loop:
    - compose.yml

- name: Run "docker compose up"
  community.docker.docker_compose_v2:
    project_src: /mnt/docker/apprise
    wait: true
    wait_timeout: 300
