---
- name: Import apprise installation tasks
  tags:
    - install-app
    - install-apprise
  block:
    - ansible.builtin.include_tasks: install.yml
    - ansible.builtin.include_tasks: traefik.yml