services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    hostname: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/docker/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /mnt/docker/traefik/config.yml:/etc/traefik/config.yml
      - /mnt/docker/traefik/certs:/etc/ssl/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik-192-168-56-18.traefik.me`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=https"
      - "traefik.http.routers.dashboard.tls=true"

networks:
  app:
    external: true