---
- name: Fail2ban | Ensure fail2ban is present
  ansible.builtin.apt:
    pkg:
      - fail2ban
    state: present

- name: Fail2ban | Ensure config files exist
  ansible.builtin.template:
    src: fail2ban.local.conf.j2
    dest: /etc/fail2ban/jail.d/
    owner: root
    group: root
    mode: 0755

- name: Fail2ban | Apply configuration (flush handlers)
  ansible.builtin.meta: flush_handlers

- name: Fail2ban | Start and enable fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
  become: true
