---
- name: Import packages configuration tasks
  ansible.builtin.import_tasks: packages.yml
  become: true
  tags:
    - install-common
    - install-packages

- name: Import user configuration tasks
  ansible.builtin.import_tasks: user.yml
  become: true
  tags:
    - install-common
    - install-user

- name: Import datetime configuration tasks
  ansible.builtin.import_tasks: datetime.yml
  become: true
  tags:
    - install-common
    - install-datetime

- name: Import iptables configuration tasks
  ansible.builtin.import_tasks: iptables.yml
  become: true
  tags:
    - install-common
    - install-iptables

- name: Import ssh configuration tasks
  ansible.builtin.import_tasks: ssh.yml
  become: true
  tags:
    - install-common
    - install-ssh
  when: not is_vagrant
