---
- name: UFW | Ensure ufw package is present
  ansible.builtin.apt:
    state: present
    package: ufw

- name: UFW | Configure ufw allow rules
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    direction: "{{ item.dir }}"
  loop:
    - { port: '80', proto: 'tcp', dir: 'in' }
    - { port: '443', proto: 'tcp', dir: 'in' }
    - { port: '80', proto: 'tcp', dir: 'out' }
    - { port: '443', proto: 'tcp', dir: 'out' }
    - { port: '53', proto: 'udp', dir: 'out' }
    # - { port: '25', proto: 'udp', dir: 'out' } // SMTP
  notify: Reload ufw


# - name: Allow netdata
#   community.general.ufw:
#     rule: allow
#     src: '172.17.0.0/16'
#     port: '19999'
#     proto: tcp
#     direction: in

- name: UFW | Limit SSH connection rate
  community.general.ufw:
    rule: limit
    port: 22
    proto: tcp
  notify: Reload ufw

- name: UFW | Enable logging
  community.general.ufw:
    logging: "on"
  notify: Reload ufw

- name: UFW | Apply configuration (flush handlers)
  ansible.builtin.meta: flush_handlers

- name: UFW | Start and enable ufw
  community.general.ufw:
    state: enabled
  become: true
