---
- name: Create main directory
  ansible.builtin.file:
    path: /mnt/docker/gotify
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0755"

- name: Create sub directories
  ansible.builtin.file:
    path: /mnt/docker/gotify/{{ item.path }}
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0755"
  with_community.general.filetree: templates/compose/
  when: item.state == "directory"

- name: Ensure config files exist
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: /mnt/docker/gotify/{{ item.path }}
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0644"
  with_community.general.filetree: templates/compose/
  when: item.state == "file"

- name: Ensure gotify systemd service installed
  ansible.builtin.template:
    src: systemd/gotify.service
    dest: /etc/systemd/system/docker-gotify.service
    mode: "0644"

- name: Make sure gotify service is running
  ansible.builtin.systemd_service:
    state: started
    name: docker-gotify.service