---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0750"
  loop:
    - /mnt/docker/uptimekuma
    - /mnt/docker/volumes/uptimekuma
    - /mnt/docker/volumes/uptimekuma/uptimekuma

- name: Ensure config files exist (0640)
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/mnt/docker/uptimekuma/{{ item }}"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0640"
  loop:
    - compose.yml

- name: Run "docker compose up"
  community.docker.docker_compose_v2:
    project_src: /mnt/docker/uptimekuma
    recreate: always
