---
- name: Create main directory
  ansible.builtin.file:
    path: /mnt/docker/uptimekuma
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0755"

- name: Create volumes directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0755"
  loop:
    - /mnt/docker/volumes/uptimekuma
    - /mnt/docker/volumes/uptimekuma/uptimekuma

- name: Ensure config files exist (0644)
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/mnt/docker/uptimekuma/{{ item }}"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0644"
  loop:
    - compose.yml

- name: Run "docker compose up"
  community.docker.docker_compose_v2:
    project_src: /mnt/docker/uptimekuma
    recreate: always
