---
- name: Create main directory
  ansible.builtin.file:
    path: /mnt/docker/graylog
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0755"

- name: Create volumes directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "1100"
    group: "1100"
    mode: "0755"
  loop:
    - /mnt/docker/volumes/graylog/graylog/data/data
    - /mnt/docker/volumes/graylog/graylog/data/config

- name: Create volumes directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0755"
  loop:
    - /mnt/docker/volumes/graylog/datanode
    - /mnt/docker/volumes/graylog/mongodb/data
    - /mnt/docker/volumes/graylog/mongodb/config

- name: Ensure config files exist
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/mnt/docker/graylog/{{ item }}"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0644"
  loop:
    - compose.yml

- name: Run "docker compose up"
  community.docker.docker_compose_v2:
    project_src: /mnt/docker/graylog
    recreate: always
