db:
  path: diun.db

watch:
  workers: 10
  schedule: "0 0 * * *"
  jitter: 30s
  firstCheckNotif: false
  runOnStartup: true

defaults:
  watchRepo: false
  notifyOn:
    - new
    - update
  sortTags: reverse

providers:
  docker:
    watchStopped: false
    watchByDefault: false
    endpoint: "unix:///var/run/docker.sock"