global:
  sendAnonymousUsage: false

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      tls:
        options: intermediate@file

providers:
  file:
    filename: "/etc/traefik/config.yml"
    watch: true
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    network: app
    exposedByDefault: false
    defaultRule: "{% raw %}HostRegexp(`{{ index .Labels \"com.docker.compose.service\"}}.traefik.me`,`{{ index .Labels \"com.docker.compose.service\"}}-{dashed-ip:.*}.traefik.me`){% endraw %}"

log:
  level: ERROR
  maxBackups: 5
  maxAge: 7
  compress: true
  noColor: true

accessLog:
  bufferingSize: 100