global:
  sendAnonymousUsage: false

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

providers:
  file:
    filename: "/etc/traefik/config.yml"
    watch: true
  swarm:
    endpoint: "tcp://127.0.0.1:2377"
    exposedByDefault: false
    network: app
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    network: app
    exposedByDefault: false

log:
  level: DEBUG
  noColor: true

accessLog:
  bufferingSize: 0