---
ubuntu_version: jammy
default_username: thomas
default_email: "{{ lookup('ansible.builtin.env', 'DEFAULT_EMAIL') }}"
timezone: Europe/Paris
default_password: "{{ lookup('ansible.builtin.env', 'DEFAULT_PASSWORD') }}"
is_vagrant: true
server_hostname: "192-168-56-18.traefik.me"
server_ip_address: "192.168.56.18"
traefik_hostname: "traefik-192-168-56-18.traefik.me"
traefik_version: "v3.0"
apprise_hostname: "apprise-192-168-56-18.traefik.me"
discord_webhook_backups: "{{ lookup('ansible.builtin.env', 'DISCORD_WEBHOOK_BACKUPS') }}"
discord_webhook_updates: "{{ lookup('ansible.builtin.env', 'DISCORD_WEBHOOK_UPDATES') }}"