---

# ------------------------------
# Global
# ------------------------------

default_username: thomas
default_email: "{{ lookup('ansible.builtin.env', 'DEFAULT_EMAIL') }}"
default_password: "{{ lookup('ansible.builtin.env', 'DEFAULT_PASSWORD') }}"
timezone: Europe/Paris
ubuntu_version: jammy


# ---------------
# Server
# ---------------
server_fqdn: 192-168-56-18.traefik.me
server_ip_address: 192.168.56.18


# ---------------
# Vagrant
# ---------------
is_vagrant: true


# ---------------
# Notifications
# ---------------
discord_webhook_backups: "{{ lookup('ansible.builtin.env', 'DISCORD_WEBHOOK_BACKUPS') }}"
discord_webhook_updates: "{{ lookup('ansible.builtin.env', 'DISCORD_WEBHOOK_UPDATES') }}"


# ---------------
# SMTP
# ---------------
smtp_host: "{{ lookup('ansible.builtin.env', 'SMTP_HOST') }}"
smtp_user: "{{ lookup('ansible.builtin.env', 'SMTP_USER') }}"
smtp_password: "{{ lookup('ansible.builtin.env', 'SMTP_PASSWORD') }}"


# ------------------------------
# Applications
# ------------------------------

# ---------------
# Apprise
# ---------------
apprise_fqdn: apprise-192-168-56-18.traefik.me
apprise_apprise_docker_image: caronc/apprise:1.1.3

# Traefik htpasswd
apprise_basic_auth_user: "{{ lookup('ansible.builtin.env', 'APPRISE_AUTH_USER') }}"
apprise_basic_auth_password: "{{ lookup('ansible.builtin.env', 'APPRISE_AUTH_PASSWORD') }}"


# ---------------
# Diun
# ---------------
diun_diun_docker_image: crazymax/diun:4.28


# ---------------
# Mealie
# ---------------
mealie_fqdn: mealie-192-168-56-18.traefik.me

mealie_mealie_docker_image: ghcr.io/mealie-recipes/mealie:v1.10.1
mealie_postgres_docker_image: postgres:15

mealie_postgres_user: "{{ lookup('ansible.builtin.env', 'MEALIE_POSTGRES_USER') }}"
mealie_postgres_password: "{{ lookup('ansible.builtin.env', 'MEALIE_POSTGRES_PASSWORD') }}"

mealie_smtp_from_name: "{{ lookup('ansible.builtin.env', 'MEALIE_SMTP_FROM_NAME') }}"
mealie_smtp_from_address: "{{ lookup('ansible.builtin.env', 'MEALIE_SMTP_FROM_ADDRESS') }}"


# ---------------
# Monitoring
# ---------------
monitoring_victoriametrics_fqdn: victoriametrics-192-168-56-18.traefik.me
monitoring_grafana_fqdn: grafana-192-168-56-18.traefik.me
monitoring_alertmanager_fqdn: alertmanager-192-168-56-18.traefik.me

monitoring_vmagent_docker_image: victoriametrics/vmagent:v1.101.0
monitoring_vmalert_docker_image: victoriametrics/vmalert:v1.101.0
monitoring_victoriametrics_docker_image: victoriametrics/victoria-metrics:v1.101.0
monitoring_alertmanager_docker_image: prom/alertmanager:v0.27.0
monitoring_grafana_docker_image: grafana/grafana:10.4.2

monitoring_grafana_smtp_from_name: "{{ lookup('ansible.builtin.env', 'GRAFANA_SMTP_FROM_NAME') }}"
monitoring_grafana_smtp_from_address: "{{ lookup('ansible.builtin.env', 'GRAFANA_SMTP_FROM_ADDRESS') }}"


# ---------------
# Traefik
# ---------------
traefik_fqdn: traefik-192-168-56-18.traefik.me
traefik_traefik_docker_image: traefik:v3.0


# ---------------
# Restic
# ---------------
restic_restic_docker_image: mazzolino/restic:1.7.2

restic_repository: "{{ lookup('ansible.builtin.env', 'B2_BUCKET_ENDPOINT') }}"
restic_password: "{{ lookup('ansible.builtin.env', 'B2_ACCOUNT_PWD') }}"
restic_aws_access_key_id: "{{ lookup('ansible.builtin.env', 'B2_APP_KEY_ID') }}"
restic_aws_secret_access_key: "{{ lookup('ansible.builtin.env', 'B2_APP_KEY') }}"