---
- name: Docker swarm | Init a new swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ server_ip_address }}"

- name: Docker swarm | Create network
  community.docker.docker_network:
    name: traefik-public
    driver: overlay
    attachable: true
    # scope: swarm
