---
# ------------------------------
# Global
# ------------------------------

default_username: ubuntu
default_password: CHANGEME
timezone: Europe/Paris
ubuntu_version: jammy


# ---------------
# Server
# ---------------
server_fqdn: CHANGEME
server_ip_address: CHANGEME
