---
# ------------------------------
# Global
# ------------------------------

default_username: thomas
default_email: CHANGEME
default_password: CHANGEME
timezone: Europe/Paris
ubuntu_version: jammy


# ---------------
# Server
# ---------------
server_fqdn: 192-168-56-18.traefik.me
server_ip_address: 192.168.56.18


# ---------------
# Vagrant
# ---------------
is_vagrant: true


# ---------------
# Notifications
# ---------------
discord_webhook_backups: CHANGEME
discord_webhook_updates: CHANGEME


# ---------------
# SMTP
# ---------------
smtp_host: CHANGEME
smtp_user: CHANGEME
smtp_password: CHANGEME


# ------------------------------
# Applications
# ------------------------------

# ---------------
# Apprise
# ---------------
apprise_fqdn: apprise-192-168-56-18.traefik.me
apprise_apprise_docker_image: caronc/apprise:1.1.3

# Traefik htpasswd
apprise_basic_auth_user: CHANGEME
apprise_basic_auth_password: CHANGEME


# ---------------
# Diun
# ---------------
diun_diun_docker_image: crazymax/diun:4.28


# ---------------
# Mealie
# ---------------
mealie_fqdn: mealie-192-168-56-18.traefik.me

mealie_mealie_docker_image: ghcr.io/mealie-recipes/mealie:v1.10.1
mealie_postgres_docker_image: postgres:15

mealie_postgres_user: CHANGEME
mealie_postgres_password: CHANGEME

mealie_smtp_from_name: Mealie
mealie_smtp_from_address: CHANGEME


# ---------------
# Monitoring
# ---------------
monitoring_victoriametrics_fqdn: victoriametrics-192-168-56-18.traefik.me
monitoring_grafana_fqdn: grafana-192-168-56-18.traefik.me
monitoring_alertmanager_fqdn: alertmanager-192-168-56-18.traefik.me

monitoring_vmagent_docker_image: victoriametrics/vmagent:v1.101.0
monitoring_vmalert_docker_image: victoriametrics/vmalert:v1.101.0
monitoring_victoriametrics_docker_image: victoriametrics/victoria-metrics:v1.101.0
monitoring_alertmanager_docker_image: prom/alertmanager:v0.27.0
monitoring_grafana_docker_image: grafana/grafana:10.4.2

monitoring_grafana_smtp_from_name: Grafana
monitoring_grafana_smtp_from_address: CHANGEME


# ---------------
# Traefik
# ---------------
traefik_fqdn: traefik-192-168-56-18.traefik.me
traefik_traefik_docker_image: traefik:v3.0

# Traefik htpasswd
traefik_basic_auth_user: CHANGEME
traefik_basic_auth_password: CHANGEME


# ---------------
# Restic
# ---------------
restic_restic_docker_image: mazzolino/restic:1.7.2

restic_repository: CHANGEME
restic_password: CHANGEME
restic_aws_access_key_id: CHANGEME
restic_aws_secret_access_key: CHANGEME


# ---------------
# Freshrss
# ---------------
freshrss_fqdn: freshrss-192-168-56-18.traefik.me
freshrss_freshrss_docker_image: linuxserver/freshrss:1.24.1


# ---------------
# Readeck
# ---------------
readeck_fqdn: readeck-192-168-56-18.traefik.me
readeck_readeck_docker_image: codeberg.org/readeck/readeck:0.14.0


# ---------------
# Zipline
# ---------------
zipline_fqdn: zipline-192-168-56-18.traefik.me

zipline_zipline_docker_image: ghcr.io/diced/zipline
zipline_postgres_docker_image: postgres:15

zipline_zipline_secret: CHANGEME
zipline_postgres_user: CHANGEME
zipline_postgres_password: CHANGEME
zipline_postgres_database: CHANGEME