---
- name: Create main directory
  ansible.builtin.file:
    path: /mnt/docker/traefik
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0755"

- name: Create sub directories
  ansible.builtin.file:
    path: "/mnt/docker/traefik/{{ item }}"
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0755"
  loop:
    - basic_auth
    - certs

- name: Ensure config files exist
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/mnt/docker/traefik/{{ item }}"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0644"
  loop:
    - compose.yml
    - config.yml
    - traefik.yml

- name: Add a user to a password file and ensure permissions are set
  community.general.htpasswd:
    path: /mnt/docker/traefik/basic_auth/traefik
    name: "{{ lookup('ansible.builtin.env', 'TRAEFIK_AUTH_USER') }}"
    password: "{{ lookup('ansible.builtin.env', 'TRAEFIK_AUTH_PASSWORD') }}"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0640"

- name: Generate local certs for traefik
  ansible.builtin.shell:
    cmd: |
      wget traefik.me/fullchain.pem -O cf_cert.pem
      wget traefik.me/privkey.pem -O cf_key.pem
    chdir: /mnt/docker/traefik/certs
  become_user: "{{ default_username }}"
  become: true
  when: is_vagrant

- name: Copy Cloudflare certs from files
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: /mnt/docker/traefik/certs/{{ item.name }}
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0640"
  loop:
    - { content: "{{ lookup('file', './data/certificates/cf_cert.pem', errors='ignore') }}", name: cf_cert.pem }
    - { content: "{{ lookup('file', './data/certificates/cf_key.pem', errors='ignore') }}", name: cf_key.pem }
  loop_control:
    label: "{{ item.name }}"
  when: not is_vagrant

- name: Run "docker compose up"
  community.docker.docker_compose_v2:
    project_src: /mnt/docker/traefik
    recreate: always
