---
- name: Create main directory
  ansible.builtin.file:
    path: /mnt/docker/traefik
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0750"

- name: Ensure config files exist
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/mnt/docker/traefik/{{ item }}"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0640"
  loop:
    - compose.yml
    - traefik.yml

- name: Ensure config files exist (0600)
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/mnt/docker/traefik/{{ item }}"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0600"
  loop:
    - acme.json

- name: Run "docker compose up"
  community.docker.docker_compose_v2:
    project_src: /mnt/docker/traefik
    recreate: always
