---
- name: Create main directory
  ansible.builtin.file:
    path: /mnt/docker/traefik
    state: directory
    owner: "{{default_username}}"
    group: "{{default_username}}"
    mode: "0750"

- name: Create sub directories
  ansible.builtin.file:
    path: /mnt/docker/traefik/{{ item.path }}
    state: directory
    owner: "{{default_username}}"
    group: "{{default_username}}"
    mode: "0750"
  with_filetree: templates/compose/
  when: item.state == 'directory'

- name: Ensure config files exist
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: /mnt/docker/traefik/{{ item.path }}
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: 0640
  with_filetree: templates/compose/
  when: item.state == 'file'

- name : Generate local certs for traefik
  ansible.builtin.shell:
    cmd: |
      wget traefik.me/fullchain.pem -O cert.pem
      wget traefik.me/privkey.pem -O key.pem
    chdir: /mnt/docker/traefik/certs
  become_user: "{{ default_username }}"
  when: is_vagrant == true


# - name: Create {{ traefik_hostname }} A record to point to {{ server_ip_address }}
#   community.general.cloudflare_dns:
#     zone: "{{ server_hostname }}"
#     record: traefik
#     type: A
#     value: "{{ server_ip_address }}"
#     account_email: "{{ cf_account_email }}"
#     account_api_token: "{{ cf_account_api_token }}"
#   register: record
#   when: is_vagrant == false

- name: Ensure Traefik systemd service installed
  ansible.builtin.template:
    src: "systemd/traefik.service"
    dest: "/etc/systemd/system/docker-traefik.service"
    mode: 0640

- name: Make sure Traefik service is running
  ansible.builtin.systemd_service:
    state: started
    name: docker-traefik.service