---
- name: Create main directory
  ansible.builtin.file:
    path: /mnt/docker/traefik
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0755"

- name: Create sub directories
  ansible.builtin.file:
    path: /mnt/docker/traefik/{{ item }}
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0755"
  loop:
    - basic_auth
    - certs
    - logs

- name: Ensure config files exist
  ansible.builtin.template:
    src: "templates/compose/{{ item }}.j2"
    dest: "/mnt/docker/traefik/{{ item }}"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0644"
  loop:
    - docker-compose.yml
    - config.yml
    - traefik.yml

- name: Add a user to a password file and ensure permissions are set
  community.general.htpasswd:
    path: /mnt/docker/traefik/basic_auth/traefik
    name: "{{ lookup('ansible.builtin.env', 'TRAEFIK_AUTH_USER') }}"
    password: "{{ lookup('ansible.builtin.env', 'TRAEFIK_AUTH_PASSWORD') }}"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0640"

- name: Generate local certs for traefik
  ansible.builtin.shell:
    cmd: |
      wget traefik.me/fullchain.pem -O cert.pem
      wget traefik.me/privkey.pem -O key.pem
    chdir: /mnt/docker/traefik/certs
  become_user: "{{ default_username }}"
  become: true
  when: is_vagrant

- name: Copy Cloudflare certs from files
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: /mnt/docker/traefik/certs/{{ item.name }}
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0640"
  loop:
    - { content: "{{ lookup('ansible.builtin.file', './data/certificates/cert.pem') }}", name: cert.pem }
    - { content: "{{ lookup('ansible.builtin.file', './data/certificates/key.pem') }}", name: key.pem }
  loop_control:
    label: "{{ item.name }}"
  when: is_vagrant == false

- name: Ensure Traefik systemd service installed
  ansible.builtin.template:
    src: systemd/traefik.service
    dest: /etc/systemd/system/docker-traefik.service
    mode: "0644"

- name: Ensure systemd is reloaded
  ansible.builtin.service:
    daemon_reload: true

- name: Make sure Traefik service is running
  ansible.builtin.systemd_service:
    name: docker-traefik.service
    enabled: true
    state: started