---
# general settings
default_username: thomas
timezone: Europe/Paris

# SSH key
host_ssh_key: "/home/thomas/.ssh/hetzner.pub"

# generate random passwords for default user and root user
default_password: "{{lookup('password', '/dev/null length=15 chars=ascii_letters,digits,punctuation')}}"
root_password: "{{lookup('password', '/dev/null length=15 chars=ascii_letters,digits,punctuation')}}"