version: '3.8'

services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: always
    ports:
      - 80:80
      - 127.0.0.1:81:81
      - 443:443
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - /mnt/docker-volumes/nginx_proxy_manager/npm_data:/data
      - /mnt/docker-volumes/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
    networks:
      - nginx_proxy_manager_network

networks:
  nginx_proxy_manager_network:
    external: true