---
- name: Create main directory
  ansible.builtin.file:
    path: /mnt/docker/beszel
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0755"

- name: Ensure config files exist
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/mnt/docker/beszel/{{ item }}"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0644"
  loop:
    - compose.yml

- name: Create volumes directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0755"
  loop:
    - /mnt/docker/volumes/beszel/data
    - /mnt/docker/volumes/beszel/socket
    - /mnt/docker/volumes/beszel/agent/data

- name: Run "docker compose up"
  community.docker.docker_compose_v2:
    project_src: /mnt/docker/beszel
    recreate: always
    wait: true