services:

  traefik:
    image: traefik:v3.0
    container_name: traefik
    hostname: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /mnt/docker/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /mnt/docker/traefik/config.yml:/etc/traefik/config.yml
      - /mnt/docker/traefik/certs:/etc/ssl/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app
      # - dev
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=app"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.rule=Host(`traefik.192.168.56.18.traefik.me`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik.service=api@internal"
      # - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      # - "traefik.http.routers.traefik.middlewares=default@file"

networks:
  app:
    external: true
  # dev:
  #   external: true