api:
  dashboard: true
  debug: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecured
  websecured:
    address: ":443"
    http:
      tls:
        options: intermediate@file

providers:
  file:
    filename: /config.yml
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false
    defaultRule: "HostRegexp(`{{ index .Labels \"com.docker.compose.service\"}}.thomassimonet.dev`)"