---
- name: Create directory
  ansible.builtin.file:
    path: /mnt/docker/cloudflared
    state: directory
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0750"

- name: Ensure config files exist
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/mnt/docker/cloudflared/{{ item }}"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0640"
  loop:
    - compose.yml
    - config.yml

- name: Copy Cloudflare tunnel certs
  ansible.builtin.copy:
    content: "{{ lookup('file', './data/certificates/tunnel_cert.pem', errors='ignore') }}"
    dest: /mnt/docker/cloudflared/cert.pem
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0640"

- name: Run "docker compose up"
  community.docker.docker_compose_v2:
    project_src: /mnt/docker/cloudflared
    recreate: always
    wait: true
